// ALL FLASHCARD DATA
// This object contains all the Korean words organized by category
const flashcardData = {
    // READING FOUNDATIONS
    "Hangul Consonants": [
        { korean: "ㄱ", romanization: "g/k", meaning: "Consonant G/K" },
        { korean: "ㄴ", romanization: "n", meaning: "Consonant N" },
        { korean: "ㄷ", romanization: "d/t", meaning: "Consonant D/T" },
        { korean: "ㄹ", romanization: "r/l", meaning: "Consonant R/L" },
        { korean: "ㅁ", romanization: "m", meaning: "Consonant M" },
        { korean: "ㅂ", romanization: "b/p", meaning: "Consonant B/P" },
        { korean: "ㅅ", romanization: "s", meaning: "Consonant S" },
        { korean: "ㅇ", romanization: "ng/silent", meaning: "Consonant NG (or silent)" },
        { korean: "ㅈ", romanization: "j", meaning: "Consonant J" },
        { korean: "ㅊ", romanization: "ch", meaning: "Consonant CH" },
        { korean: "ㅋ", romanization: "k", meaning: "Consonant K" },
        { korean: "ㅌ", romanization: "t", meaning: "Consonant T" },
        { korean: "ㅍ", romanization: "p", meaning: "Consonant P" },
        { korean: "ㅎ", romanization: "h", meaning: "Consonant H" },
        { korean: "ㄲ", romanization: "kk", meaning: "Double Consonant KK" },
        { korean: "ㄸ", romanization: "tt", meaning: "Double Consonant TT" },
        { korean: "ㅃ", romanization: "pp", meaning: "Double Consonant PP" },
        { korean: "ㅆ", romanization: "ss", meaning: "Double Consonant SS" },
        { korean: "ㅉ", romanization: "jj", meaning: "Double Consonant JJ" }
    ],

    "Hangul Vowels": [
        { korean: "ㅏ", romanization: "a", meaning: "Vowel A" },
        { korean: "ㅑ", romanization: "ya", meaning: "Vowel YA" },
        { korean: "ㅓ", romanization: "eo", meaning: "Vowel EO" },
        { korean: "ㅕ", romanization: "yeo", meaning: "Vowel YEO" },
        { korean: "ㅗ", romanization: "o", meaning: "Vowel O" },
        { korean: "ㅛ", romanization: "yo", meaning: "Vowel YO" },
        { korean: "ㅜ", romanization: "u", meaning: "Vowel U" },
        { korean: "ㅠ", romanization: "yu", meaning: "Vowel YU" },
        { korean: "ㅡ", romanization: "eu", meaning: "Vowel EU" },
        { korean: "ㅣ", romanization: "i", meaning: "Vowel I" },
        { korean: "ㅐ", romanization: "ae", meaning: "Vowel AE" },
        { korean: "ㅒ", romanization: "yae", meaning: "Vowel YAE" },
        { korean: "ㅔ", romanization: "e", meaning: "Vowel E" },
        { korean: "ㅖ", romanization: "ye", meaning: "Vowel YE" },
        { korean: "ㅘ", romanization: "wa", meaning: "Vowel WA" },
        { korean: "ㅙ", romanization: "wae", meaning: "Vowel WAE" },
        { korean: "ㅚ", romanization: "oe/we", meaning: "Vowel OE/WE" },
        { korean: "ㅝ", romanization: "wo", meaning: "Vowel WO" },
        { korean: "ㅞ", romanization: "we", meaning: "Vowel WE" },
        { korean: "ㅟ", romanization: "wi", meaning: "Vowel WI" },
        { korean: "ㅢ", romanization: "ui", meaning: "Vowel UI" }
    ],

    "Basic Syllables": [
        { korean: "가", romanization: "ga", meaning: "GA syllable" },
        { korean: "나", romanization: "na", meaning: "NA syllable" },
        { korean: "다", romanization: "da", meaning: "DA syllable" },
        { korean: "라", romanization: "ra", meaning: "RA syllable" },
        { korean: "마", romanization: "ma", meaning: "MA syllable" },
        { korean: "바", romanization: "ba", meaning: "BA syllable" },
        { korean: "사", romanization: "sa", meaning: "SA syllable" },
        { korean: "아", romanization: "a", meaning: "A syllable" },
        { korean: "자", romanization: "ja", meaning: "JA syllable" },
        { korean: "차", romanization: "cha", meaning: "CHA syllable" },
        { korean: "카", romanization: "ka", meaning: "KA syllable" },
        { korean: "타", romanization: "ta", meaning: "TA syllable" },
        { korean: "파", romanization: "pa", meaning: "PA syllable" },
        { korean: "하", romanization: "ha", meaning: "HA syllable" }
    ],

    // NUMBERS
    "Native Korean Numbers (1-20)": [
        { korean: "하나", romanization: "hana", meaning: "One" },
        { korean: "둘", romanization: "dul", meaning: "Two" },
        { korean: "셋", romanization: "set", meaning: "Three" },
        { korean: "넷", romanization: "net", meaning: "Four" },
        { korean: "다섯", romanization: "daseot", meaning: "Five" },
        { korean: "여섯", romanization: "yeoseot", meaning: "Six" },
        { korean: "일곱", romanization: "ilgop", meaning: "Seven" },
        { korean: "여덟", romanization: "yeodeol", meaning: "Eight" },
        { korean: "아홉", romanization: "ahop", meaning: "Nine" },
        { korean: "열", romanization: "yeol", meaning: "Ten" },
        { korean: "열하나", romanization: "yeol-hana", meaning: "Eleven" },
        { korean: "열둘", romanization: "yeol-dul", meaning: "Twelve" },
        { korean: "열셋", romanization: "yeol-set", meaning: "Thirteen" },
        { korean: "열넷", romanization: "yeol-net", meaning: "Fourteen" },
        { korean: "열다섯", romanization: "yeol-daseot", meaning: "Fifteen" },
        { korean: "열여섯", romanization: "yeol-yeoseot", meaning: "Sixteen" },
        { korean: "열일곱", romanization: "yeol-ilgop", meaning: "Seventeen" },
        { korean: "열여덟", romanization: "yeol-yeodeol", meaning: "Eighteen" },
        { korean: "열아홉", romanization: "yeol-ahop", meaning: "Nineteen" },
        { korean: "스물", romanization: "seumul", meaning: "Twenty" }
    ],

    "Sino-Korean Numbers (1-20)": [
        { korean: "일", romanization: "il", meaning: "One" },
        { korean: "이", romanization: "i", meaning: "Two" },
        { korean: "삼", romanization: "sam", meaning: "Three" },
        { korean: "사", romanization: "sa", meaning: "Four" },
        { korean: "오", romanization: "o", meaning: "Five" },
        { korean: "육", romanization: "yuk", meaning: "Six" },
        { korean: "칠", romanization: "chil", meaning: "Seven" },
        { korean: "팔", romanization: "pal", meaning: "Eight" },
        { korean: "구", romanization: "gu", meaning: "Nine" },
        { korean: "십", romanization: "sip", meaning: "Ten" },
        { korean: "십일", romanization: "sip-il", meaning: "Eleven" },
        { korean: "십이", romanization: "sip-i", meaning: "Twelve" },
        { korean: "십삼", romanization: "sip-sam", meaning: "Thirteen" },
        { korean: "십사", romanization: "sip-sa", meaning: "Fourteen" },
        { korean: "십오", romanization: "sip-o", meaning: "Fifteen" },
        { korean: "십육", romanization: "sip-yuk", meaning: "Sixteen" },
        { korean: "십칠", romanization: "sip-chil", meaning: "Seventeen" },
        { korean: "십팔", romanization: "sip-pal", meaning: "Eighteen" },
        { korean: "십구", romanization: "sip-gu", meaning: "Nineteen" },
        { korean: "이십", romanization: "i-sip", meaning: "Twenty" },
        { korean: "백", romanization: "baek", meaning: "One hundred" }
    ],

    // DAILY LIFE
    "Basic Greetings": [
        { korean: "안녕하세요", romanization: "annyeonghaseyo", meaning: "Hello / Goodbye (polite)" },
        { korean: "안녕", romanization: "annyeong", meaning: "Hi / Bye (casual)" },
        { korean: "안녕히 가세요", romanization: "annyeonghi gaseyo", meaning: "Goodbye (to person leaving)" },
        { korean: "안녕히 계세요", romanization: "annyeonghi gyeseyo", meaning: "Goodbye (you are leaving)" },
        { korean: "좋은 아침", romanization: "joeun achim", meaning: "Good morning" },
        { korean: "잘 자", romanization: "jal ja", meaning: "Good night (casual)" },
        { korean: "잘 자요", romanization: "jal jayo", meaning: "Good night (polite)" },
        { korean: "또 봐요", romanization: "tto bwayo", meaning: "See you again" },
        { korean: "다음에 봐요", romanization: "daeume bwayo", meaning: "See you next time" },
        { korean: "어서 오세요", romanization: "eoseo oseyo", meaning: "Welcome" },
        { korean: "반가워요", romanization: "bangawoyo", meaning: "Nice to meet you (casual)" },
        { korean: "반갑습니다", romanization: "bangapsumnida", meaning: "Nice to meet you (formal)" },
        { korean: "잘 가요", romanization: "jal gayo", meaning: "Goodbye (casual)" }
    ],

    "Polite Expressions": [
        { korean: "감사합니다", romanization: "gamsahamnida", meaning: "Thank you (formal)" },
        { korean: "고맙습니다", romanization: "gomapseumnida", meaning: "Thank you (polite)" },
        { korean: "고마워", romanization: "gomawo", meaning: "Thanks (casual)" },
        { korean: "고마워요", romanization: "gomawoyo", meaning: "Thanks (polite casual)" },
        { korean: "죄송합니다", romanization: "joesonghamnida", meaning: "I'm sorry (formal)" },
        { korean: "미안해요", romanization: "mianhaeyo", meaning: "I'm sorry (polite)" },
        { korean: "미안", romanization: "mian", meaning: "Sorry (casual)" },
        { korean: "괜찮아요", romanization: "gwaenchanayo", meaning: "It's okay / Are you okay?" },
        { korean: "실례합니다", romanization: "sillyehamnida", meaning: "Excuse me (formal interrupt)" },
        { korean: "실례지만", romanization: "sillyejiman", meaning: "Excuse me (sorry in advance)" },
        { korean: "잠시만요", romanization: "jamsimanyo", meaning: "Just a moment" },
        { korean: "천만에요", romanization: "cheonmaneyo", meaning: "You're welcome" },
        { korean: "아니야", romanization: "aniya", meaning: "You're welcome (casual)" },
        { korean: "아니에요", romanization: "anieyo", meaning: "You're welcome (formal)" },
        { korean: "여기요", romanization: "yeogiyo", meaning: "Excuse me (to get waiter's attention)" },
        { korean: "저기요", romanization: "jeogiyo", meaning: "Excuse me (to get waiter's attention)" },
        { korean: "우와", romanization: "uwa", meaning: "Wow" }
    ],

    "Yes / No / Common Responses": [
        { korean: "네", romanization: "ne", meaning: "Yes" },
        { korean: "응", romanization: "eung", meaning: "Yeah (casual)" },
        { korean: "아니요", romanization: "aniyo", meaning: "No" },
        { korean: "아니", romanization: "ani", meaning: "No (casual)" },
        { korean: "알겠습니다", romanization: "algesseumnida", meaning: "I understand / Okay (formal)" },
        { korean: "알았어", romanization: "arasseo", meaning: "Got it / Okay (casual)" },
        { korean: "물론", romanization: "mullon", meaning: "Of course" },
        { korean: "그래요", romanization: "geuraeyo", meaning: "That's right / I see" },
        { korean: "아마", romanization: "ama", meaning: "Maybe / Perhaps" },
        { korean: "정말요?", romanization: "jeongmallyo?", meaning: "Really?" }
    ],

    // PEOPLE & PRONOUNS
    "Family Members": [
        { korean: "아버지", romanization: "abeoji", meaning: "Father (formal)" },
        { korean: "아빠", romanization: "appa", meaning: "Dad" },
        { korean: "어머니", romanization: "eomeoni", meaning: "Mother (formal)" },
        { korean: "엄마", romanization: "eomma", meaning: "Mom" },
        { korean: "할아버지", romanization: "harabeoji", meaning: "Grandfather" },
        { korean: "할머니", romanization: "halmeoni", meaning: "Grandmother" },
        { korean: "형", romanization: "hyeong", meaning: "Older brother (male speaker)" },
        { korean: "오빠", romanization: "oppa", meaning: "Older brother (female speaker)" },
        { korean: "누나", romanization: "nuna", meaning: "Older sister (male speaker)" },
        { korean: "언니", romanization: "eonni", meaning: "Older sister (female speaker)" },
        { korean: "동생", romanization: "dongsaeng", meaning: "Younger sibling" },
        { korean: "남동생", romanization: "namdongsaeng", meaning: "Younger brother" },
        { korean: "여동생", romanization: "yeodongsaeng", meaning: "Younger sister" },
        { korean: "딸", romanization: "ttal", meaning: "Daughter" },
        { korean: "아기", romanization: "agi", meaning: "Baby" },
        { korean: "아이", romanization: "ai", meaning: "Child" }
    ],

    "Pronouns": [
        { korean: "나", romanization: "na", meaning: "I / Me (casual)" },
        { korean: "저", romanization: "jeo", meaning: "I / Me (polite)" },
        { korean: "너", romanization: "neo", meaning: "You (casual)" },
        { korean: "당신", romanization: "dangsin", meaning: "You (formal)" },
        { korean: "우리", romanization: "uri", meaning: "We / Us" },
        { korean: "그", romanization: "geu", meaning: "He / Him" },
        { korean: "그녀", romanization: "geunyeo", meaning: "She / Her" },
        { korean: "이것", romanization: "igeot", meaning: "This" },
        { korean: "그것", romanization: "geugeot", meaning: "That" },
        { korean: "저것", romanization: "jeogeot", meaning: "That (over there)" },
        { korean: "누구", romanization: "nugu", meaning: "Who" }
    ],

    "Titles": [
        { korean: "선생님", romanization: "seonsaengnim", meaning: "Teacher" },
        { korean: "학생", romanization: "haksaeng", meaning: "Student" },
        { korean: "사장님", romanization: "sajangnim", meaning: "Boss / President" },
        { korean: "친구", romanization: "chingu", meaning: "Friend" },
        { korean: "의사", romanization: "uisa", meaning: "Doctor" },
        { korean: "간호사", romanization: "ganhosa", meaning: "Nurse" },
        { korean: "경찰", romanization: "gyeongchal", meaning: "Police" },
        { korean: "회사원", romanization: "hoesawon", meaning: "Office worker" },
        { korean: "농부", romanization: "nongbu", meaning: "Farmer" },
        { korean: "어부", romanization: "eobu", meaning: "Fisherman" }
    ],

    // VOCABULARY GROUPS
    "Fruits": [
        { korean: "사과", romanization: "sagwa", meaning: "Apple" },
        { korean: "바나나", romanization: "banana", meaning: "Banana" },
        { korean: "딸기", romanization: "ttalgi", meaning: "Strawberry" },
        { korean: "포도", romanization: "podo", meaning: "Grape" },
        { korean: "수박", romanization: "subak", meaning: "Watermelon" },
        { korean: "오렌지", romanization: "orenji", meaning: "Orange" },
        { korean: "배", romanization: "bae", meaning: "Pear" },
        { korean: "복숭아", romanization: "boksunga", meaning: "Peach" },
        { korean: "레몬", romanization: "remon", meaning: "Lemon" },
        { korean: "키위", romanization: "kiwi", meaning: "Kiwi" },
        { korean: "보치", romanization: "bochi", meaning: "Cherry" }
    ],

    "Vegetables": [
        { korean: "당근", romanization: "danggeun", meaning: "Carrot" },
        { korean: "양파", romanization: "yangpa", meaning: "Onion" },
        { korean: "토마토", romanization: "tomato", meaning: "Tomato" },
        { korean: "오이", romanization: "oi", meaning: "Cucumber" },
        { korean: "감자", romanization: "gamja", meaning: "Potato" },
        { korean: "고구마", romanization: "goguma", meaning: "Sweet potato" },
        { korean: "배추", romanization: "baechu", meaning: "Cabbage" },
        { korean: "무", romanization: "mu", meaning: "Radish" },
        { korean: "마늘", romanization: "maneul", meaning: "Garlic" },
        { korean: "버섯", romanization: "beoseot", meaning: "Mushroom" }
    ],

    "Food": [
        { korean: "밥", romanization: "bap", meaning: "Rice / Meal" },
        { korean: "김치", romanization: "gimchi", meaning: "Kimchi" },
        { korean: "국", romanization: "guk", meaning: "Soup" },
        { korean: "찌게", romanization: "jjige", meaning: "Stew" },
        { korean: "빵", romanization: "ppang", meaning: "Bread" },
        { korean: "고기", romanization: "gogi", meaning: "Meat" },
        { korean: "생선", romanization: "saengseon", meaning: "Fish" },
        { korean: "계란", romanization: "gyeran", meaning: "Egg" },
        { korean: "우유", romanization: "uyu", meaning: "Milk" },
        { korean: "라면", romanization: "ramyeon", meaning: "Ramen" },
        { korean: "치킨", romanization: "chikin", meaning: "Chicken" },
        { korean: "팝콘", romanization: "papkon", meaning: "Popcorn" },
        { korean: "핫도그", romanization: "hatdogu", meaning: "Hotdog" },
        { korean: "케이크", romanization: "keikeu", meaning: "Cake" },
        { korean: "초코", romanization: "choko", meaning: "Chocolate" },
        { korean: "씨앗", romanization: "ssiat", meaning: "Seeds" }
    ],

    "Drinks": [
        { korean: "물", romanization: "mul", meaning: "Water" },
        { korean: "커피", romanization: "keopi", meaning: "Coffee" },
        { korean: "차", romanization: "cha", meaning: "Tea" },
        { korean: "주스", romanization: "juseu", meaning: "Juice" },
        { korean: "맥주", romanization: "maekju", meaning: "Beer" },
        { korean: "소주", romanization: "soju", meaning: "Soju" },
        { korean: "우유", romanization: "uyu", meaning: "Milk" },
        { korean: "콜라", romanization: "kolla", meaning: "Cola" },
        { korean: "녹차", romanization: "nokcha", meaning: "Green tea" },
        { korean: "와인", romanization: "wain", meaning: "Wine" }
    ],

    "Colors": [
        { korean: "빨강", romanization: "ppalgang", meaning: "Red" },
        { korean: "파랑", romanization: "parang", meaning: "Blue" },
        { korean: "노랑", romanization: "norang", meaning: "Yellow" },
        { korean: "초록", romanization: "chorok", meaning: "Green" },
        { korean: "검정", romanization: "geomjeong", meaning: "Black" },
        { korean: "하양", romanization: "hayang", meaning: "White" },
        { korean: "주황", romanization: "juhwang", meaning: "Orange" },
        { korean: "분홍", romanization: "bunhong", meaning: "Pink" },
        { korean: "보라", romanization: "bora", meaning: "Purple" },
        { korean: "갈색", romanization: "galsaek", meaning: "Brown" }
    ],

    "Animals": [
        { korean: "개", romanization: "gae", meaning: "Dog" },
        { korean: "고양이", romanization: "goyangi", meaning: "Cat" },
        { korean: "새", romanization: "sae", meaning: "Bird" },
        { korean: "물고기", romanization: "mulgogi", meaning: "Fish" },
        { korean: "말", romanization: "mal", meaning: "Horse" },
        { korean: "소", romanization: "so", meaning: "Cow" },
        { korean: "돼지", romanization: "dwaeji", meaning: "Pig" },
        { korean: "닭", romanization: "dak", meaning: "Chicken" },
        { korean: "호랑이", romanization: "horangi", meaning: "Tiger" },
        { korean: "곰", romanization: "gom", meaning: "Bear" },
        { korean: "오리", romanization: "ori", meaning: "Duck" },
        { korean: "기린", romanization: "girin", meaning: "Giraffe" },
        { korean: "거미", romanization: "geomi", meaning: "Spider" },
        { korean: "개미", romanization: "gaemi", meaning: "Ant" },
        { korean: "모기", romanization: "mogi", meaning: "Mosquito" },
        { korean: "뱀", romanization: "baem", meaning: "Snake" },
        { korean: "악어", romanization: "ageo", meaning: "Crocodile" },
        { korean: "거북이", romanization: "geobugi", meaning: "Turtle" },
        { korean: "개구리", romanization: "gaeguri", meaning: "Frog" },
        { korean: "타조", romanization: "tajo", meaning: "Ostrich" }
    ],

    // TIME & ROUTINE
    "Days of the Week": [
        { korean: "월요일", romanization: "woryoil", meaning: "Monday" },
        { korean: "화요일", romanization: "hwayoil", meaning: "Tuesday" },
        { korean: "수요일", romanization: "suyoil", meaning: "Wednesday" },
        { korean: "목요일", romanization: "mogyoil", meaning: "Thursday" },
        { korean: "금요일", romanization: "geumyoil", meaning: "Friday" },
        { korean: "토요일", romanization: "toyoil", meaning: "Saturday" },
        { korean: "일요일", romanization: "ilyoil", meaning: "Sunday" }
    ],

    "Time Words": [
        { korean: "시", romanization: "si", meaning: "Hour / O'clock" },
        { korean: "시간", romanization: "sigan", meaning: "Time" },
        { korean: "분", romanization: "bun", meaning: "Minute" },
        { korean: "초", romanization: "cho", meaning: "Second" },
        { korean: "오전", romanization: "ojeon", meaning: "Morning (AM)" },
        { korean: "오후", romanization: "ohu", meaning: "Afternoon (PM)" },
        { korean: "어제", romanization: "eoje", meaning: "Yesterday" },
        { korean: "오늘", romanization: "oneul", meaning: "Today" },
        { korean: "내일", romanization: "naeil", meaning: "Tomorrow" },
        { korean: "지금", romanization: "jigeum", meaning: "Now" },
        { korean: "나중에", romanization: "najunge", meaning: "Later" },
        { korean: "아까", romanization: "akka", meaning: "A while ago" },
        { korean: "있다가", romanization: "itdaga", meaning: "For a while / After a while" },
        { korean: "곧", romanization: "got", meaning: "Soon" },
        { korean: "날", romanization: "nal", meaning: "Day" },
        { korean: "밤", romanization: "bam", meaning: "Night" },
        { korean: "낮잠", romanization: "natjam", meaning: "Nap time" },
        { korean: "낮", romanization: "nat", meaning: "Day / Daytime" },
        { korean: "날마다", romanization: "nalmada", meaning: "Everyday" },
        { korean: "매일", romanization: "maeil", meaning: "Everyday" },
        { korean: "달력", romanization: "dallyeok", meaning: "Calendar" },
        { korean: "늦게", romanization: "neutge", meaning: "Late" },
        { korean: "자주", romanization: "jaju", meaning: "Often" }
    ],

    "Daily Activities": [
        { korean: "먹다", romanization: "meokda", meaning: "To eat" },
        { korean: "자다", romanization: "jada", meaning: "To sleep" },
        { korean: "공부하다", romanization: "gongbuhada", meaning: "To study" },
        { korean: "일하다", romanization: "ilhada", meaning: "To work" },
        { korean: "가다", romanization: "gada", meaning: "To go" },
        { korean: "오다", romanization: "oda", meaning: "To come" },
        { korean: "보다", romanization: "boda", meaning: "To see / watch" },
        { korean: "듣다", romanization: "deutda", meaning: "To hear / listen" },
        { korean: "말하다", romanization: "malhada", meaning: "To speak" },
        { korean: "쓰다", romanization: "sseuda", meaning: "To write" },
        { korean: "좋아하다", romanization: "joahada", meaning: "To like" },
        { korean: "이다", romanization: "ida", meaning: "To be" },
        { korean: "가지다", romanization: "gajida", meaning: "To have / To carry" },
        { korean: "만들다", romanization: "mandeulda", meaning: "To make" },
        { korean: "배우다", romanization: "baeuda", meaning: "To learn" },
        { korean: "알다", romanization: "alda", meaning: "To know" },
        { korean: "닫다", romanization: "datda", meaning: "To close" },
        { korean: "마무리", romanization: "mamuri", meaning: "To pack up / To finish" },
        { korean: "입다", romanization: "ipda", meaning: "To wear" },
        { korean: "같다", romanization: "gatda", meaning: "To be the same" },
        { korean: "닦다", romanization: "dakda", meaning: "To brush / To swipe / To wipe" },
        { korean: "재미있다", romanization: "jaemiitda", meaning: "To be fun / Interesting" },
        { korean: "나가다", romanization: "nagada", meaning: "To go out(side)" },
        { korean: "받다", romanization: "batda", meaning: "To receive" },
        { korean: "닫다요", romanization: "datdayo", meaning: "Close" },
        { korean: "걸어요", romanization: "georeoyo", meaning: "Walking" },
        { korean: "공부", romanization: "gongbu", meaning: "Study" },
        { korean: "봉사", romanization: "bongsa", meaning: "Volunteering" },
        { korean: "이해해요", romanization: "ihaehaeyo", meaning: "Understanding" },
        { korean: "사요", romanization: "sayo", meaning: "Buy" },
        { korean: "원하다", romanization: "wonhada", meaning: "To want" },
        { korean: "원해요", romanization: "wonhaeyo", meaning: "Want (conjugated)" },
        { korean: "가지고 싶다", romanization: "gajigo sipda", meaning: "Want to have" },
        { korean: "실례하다", romanization: "sillyehada", meaning: "To do a discourtesy" }
    ],

    // SURVIVAL KOREAN
    "Transportation": [
        { korean: "버스", romanization: "beoseu", meaning: "Bus" },
        { korean: "지하철", romanization: "jihacheol", meaning: "Subway" },
        { korean: "택시", romanization: "taeksi", meaning: "Taxi" },
        { korean: "기차", romanization: "gicha", meaning: "Train" },
        { korean: "비행기", romanization: "bihaenggi", meaning: "Airplane" },
        { korean: "자전거", romanization: "jajeon-geo", meaning: "Bicycle" },
        { korean: "자동차", romanization: "jadongcha", meaning: "Car" },
        { korean: "오토바이", romanization: "otobai", meaning: "Motorcycle" }
    ],

    "Places": [
        { korean: "학교", romanization: "hakgyo", meaning: "School" },
        { korean: "병원", romanization: "byeongwon", meaning: "Hospital" },
        { korean: "가게", romanization: "gage", meaning: "Store / Shop" },
        { korean: "식당", romanization: "sikdang", meaning: "Restaurant" },
        { korean: "집", romanization: "jip", meaning: "House / Home" },
        { korean: "회사", romanization: "hoesa", meaning: "Company / Office" },
        { korean: "은행", romanization: "eunhaeng", meaning: "Bank" },
        { korean: "우체국", romanization: "ucheguk", meaning: "Post office" },
        { korean: "공항", romanization: "gonghang", meaning: "Airport" },
        { korean: "역", romanization: "yeok", meaning: "Station" },
        { korean: "방", romanization: "bang", meaning: "Room" },
        { korean: "부엌", romanization: "bueok", meaning: "Kitchen" },
        { korean: "화장실", romanization: "hwajangsil", meaning: "Comfort room / Bathroom" },
        { korean: "곳", romanization: "got", meaning: "Place" },
        { korean: "빵집", romanization: "ppangjib", meaning: "Bakery" },
        { korean: "약국", romanization: "yakguk", meaning: "Pharmacy" },
        { korean: "농사", romanization: "nongsa", meaning: "Farm field" },
        { korean: "숲", romanization: "sup", meaning: "Forest" },
        { korean: "바다", romanization: "bada", meaning: "Sea" }
    ],

    "Directions & Locations": [
        { korean: "왼쪽", romanization: "oenjjok", meaning: "Left" },
        { korean: "오른쪽", romanization: "oreunjjok", meaning: "Right" },
        { korean: "직진", romanization: "jikjin", meaning: "Straight" },
        { korean: "앞", romanization: "ap", meaning: "Front" },
        { korean: "뒤", romanization: "dwi", meaning: "Back" },
        { korean: "위", romanization: "wi", meaning: "Above / On" },
        { korean: "아래", romanization: "arae", meaning: "Below / Under" },
        { korean: "안", romanization: "an", meaning: "Inside" },
        { korean: "밖", romanization: "bak", meaning: "Outside" },
        { korean: "옆", romanization: "yeop", meaning: "Side / Next to" },
        { korean: "아래", romanization: "mit", meaning: "Under" },
        { korean: "사이", romanization: "sai", meaning: "In-between" },
        { korean: "여기", romanization: "yeogi", meaning: "Here" },
        { korean: "저기", romanization: "jeogi", meaning: "Over there" },
        { korean: "어디", romanization: "eodi", meaning: "Where" }
    ],

    "Question Words": [
        { korean: "왜", romanization: "wae", meaning: "Why" },
        { korean: "누구", romanization: "nugu", meaning: "Who" },
        { korean: "어디", romanization: "eodi", meaning: "Where" },
        { korean: "뭐", romanization: "mwo", meaning: "What" },
        { korean: "언제", romanization: "onje", meaning: "When" },
        { korean: "어느", romanization: "eoneu", meaning: "Which" },
        { korean: "이름이 뭐예요", romanization: "ireumi mwoyeyo", meaning: "What is your name?" },
        { korean: "어때요", romanization: "eottaeyo", meaning: "How about?" }
    ],

    // BODY PARTS
    "Body Parts": [
        { korean: "몸", romanization: "mom", meaning: "Body" },
        { korean: "목", romanization: "mok", meaning: "Neck" },
        { korean: "귀", romanization: "gwi", meaning: "Ear" },
        { korean: "입", romanization: "ip", meaning: "Mouth" },
        { korean: "다리", romanization: "dari", meaning: "Leg / Bridge" },
        { korean: "어깨", romanization: "eokkae", meaning: "Shoulder" }
    ],

    // HOUSEHOLD & OBJECTS
    "Household Items": [
        { korean: "가방", romanization: "gabang", meaning: "Bag" },
        { korean: "연필", romanization: "yeonpil", meaning: "Pencil" },
        { korean: "우산", romanization: "usan", meaning: "Umbrella" },
        { korean: "주전자", romanization: "jujeonja", meaning: "Kettle" },
        { korean: "손수레", romanization: "sonsure", meaning: "Pushcart" },
        { korean: "대야", romanization: "daeya", meaning: "Basin" },
        { korean: "구두", romanization: "gudu", meaning: "Shoes" },
        { korean: "유리", romanization: "yuri", meaning: "Glass" },
        { korean: "도마", romanization: "doma", meaning: "Chopping board" },
        { korean: "바구니", romanization: "baguni", meaning: "Basket" },
        { korean: "세수 비누", romanization: "sesu binu", meaning: "Facial soap" },
        { korean: "옷", romanization: "ot", meaning: "Clothes" },
        { korean: "쓰레기받기", romanization: "sseuregibatgi", meaning: "Dustpan" },
        { korean: "바가지", romanization: "bagaji", meaning: "Dipper (tabo)" },
        { korean: "치마", romanization: "chima", meaning: "Skirt" },
        { korean: "기타", romanization: "gita", meaning: "Guitar" },
        { korean: "한복", romanization: "hanbok", meaning: "Traditional clothes" },
        { korean: "머릿띠", romanization: "meoritti", meaning: "Headband" },
        { korean: "빗", romanization: "bit", meaning: "Comb" },
        { korean: "낫", romanization: "nat", meaning: "Sickle" }
    ],

    // ADJECTIVES & DESCRIPTORS
    "Adjectives & Descriptors": [
        { korean: "좋아요", romanization: "joayo", meaning: "Good" },
        { korean: "쉬워요", romanization: "swiwoyo", meaning: "Easy" },
        { korean: "싸요", romanization: "ssayo", meaning: "Cheap" },
        { korean: "매운", romanization: "maeun", meaning: "Spicy" },
        { korean: "즉시", romanization: "jeukssi", meaning: "Immediately" },
        { korean: "행복", romanization: "haengbok", meaning: "Happiness" },
        { korean: "불", romanization: "bul", meaning: "Light / Fire" },
        { korean: "풀", romanization: "pul", meaning: "Grass" },
        { korean: "빛", romanization: "bit", meaning: "Ray of light" }
    ],

    // MISCELLANEOUS
    "Miscellaneous": [
        { korean: "영화", romanization: "yeonghwa", meaning: "Movie" },
        { korean: "과", romanization: "gwa", meaning: "Chapter" },
        { korean: "지게차", romanization: "jigeecha", meaning: "Forklift" },
        { korean: "동전", romanization: "dongjeon", meaning: "Coins" },
        { korean: "흙", romanization: "heuk", meaning: "Soil" },
        { korean: "야구", romanization: "yagu", meaning: "Baseball" },
        { korean: "요가", romanization: "yoga", meaning: "Leisure / Yoga" },
        { korean: "약", romanization: "yak", meaning: "Medicine" },
        { korean: "안내", romanization: "annae", meaning: "Information / Guide" },
        { korean: "온도", romanization: "ondo", meaning: "Temperature" },
        { korean: "달", romanization: "dal", meaning: "Moon / Month" },
        { korean: "열", romanization: "yeol", meaning: "Fever" },
        { korean: "목소리", romanization: "moksori", meaning: "Voice" },
        { korean: "언어", romanization: "eoneo", meaning: "Language" },
        { korean: "말", romanization: "mal", meaning: "Word / Speech" },
        { korean: "이름", romanization: "ireum", meaning: "Name" },
        { korean: "제 이름은", romanization: "je ireumeun", meaning: "My name is" },
        { korean: "나이", romanization: "nai", meaning: "Age" },
        { korean: "연세", romanization: "yeonse", meaning: "Age (polite)" },
        { korean: "세", romanization: "se", meaning: "Age / Bird" },
        { korean: "기", romanization: "gi", meaning: "Machine" },
        { korean: "키", romanization: "ki", meaning: "Height" },
        { korean: "소개", romanization: "sogae", meaning: "Introduction" },
        { korean: "미트", romanization: "mit", meaning: "Etc. / As follows" },
        { korean: "실례", romanization: "sillye", meaning: "Discourtesy" },
        { korean: "또", romanization: "to", meaning: "Also / To" },
        { korean: "이야기", romanization: "iyagi", meaning: "Story" },
        { korean: "에요", romanization: "eyo", meaning: "To be (after vowel)" },
        { korean: "이에요", romanization: "ieyo", meaning: "To be (after consonant)" },
        { korean: "입", romanization: "ip", meaning: "Leaf / Mouth" }
    ]
};