// ALL FLASHCARD DATA - EPS TOPIK BOOK 1 AND 2
// This object contains all the Korean words organized by category

const flashcardData = {
    // ANIMALS
    "Animals": [
        { korean: "개", romanization: "gae", meaning: "Dog" },
        { korean: "강아지", romanization: "gangaji", meaning: "Puppy" },
        { korean: "고양이", romanization: "goyangi", meaning: "Cat" },
        { korean: "토끼", romanization: "tokki", meaning: "Rabbit" },
        { korean: "쥐", romanization: "jwi", meaning: "Mouse" },
        { korean: "새", romanization: "sae", meaning: "Bird" },
        { korean: "개구리", romanization: "gaeguri", meaning: "Frog" },
        { korean: "뱀", romanization: "baem", meaning: "Snake" },
        { korean: "까치", romanization: "kkachi", meaning: "Magpie" },
        { korean: "귀뚜라미", romanization: "gwittulami", meaning: "Cricket" }
    ],

    "Animal Farm": [
        { korean: "닭", romanization: "dak", meaning: "Chicken" },
        { korean: "소", romanization: "so", meaning: "Cow" },
        { korean: "오리", romanization: "ori", meaning: "Duck" },
        { korean: "물고기", romanization: "mulgogi", meaning: "Fish" },
        { korean: "염소", romanization: "yeomso", meaning: "Goat" },
        { korean: "말", romanization: "mal", meaning: "Horse" },
        { korean: "돼지", romanization: "dwaeji", meaning: "Pig" },
        { korean: "양", romanization: "yang", meaning: "Sheep" },
        { korean: "황소", romanization: "hwangso", meaning: "Ox" }
    ],

    "Wild Animals": [
        { korean: "호랑이", romanization: "horangi", meaning: "Tiger" },
        { korean: "사자", romanization: "saja", meaning: "Lion" },
        { korean: "여우", romanization: "yeou", meaning: "Fox" },
        { korean: "코끼리", romanization: "kokkiri", meaning: "Elephant" },
        { korean: "원숭이", romanization: "wonsungi", meaning: "Monkey" },
        { korean: "곰", romanization: "gom", meaning: "Bear" },
        { korean: "기린", romanization: "girin", meaning: "Giraffe" },
        { korean: "타조", romanization: "tajo", meaning: "Ostrich" }
    ],

    // OBJECTS
    "Objects 1": [
        { korean: "칠판", romanization: "chilpan", meaning: "Whiteboard/Blackboard" },
        { korean: "책", romanization: "chaek", meaning: "Book" },
        { korean: "공책", romanization: "gongchaek", meaning: "Notebook" },
        { korean: "연필", romanization: "yeonpil", meaning: "Pencil" },
        { korean: "볼펜", romanization: "bolpen", meaning: "Ball pen" },
        { korean: "지우개", romanization: "jiugae", meaning: "Eraser" },
        { korean: "필통", romanization: "piltong", meaning: "Pencil case" },
        { korean: "시계", romanization: "sigye", meaning: "Clock" },
        { korean: "달력", romanization: "dallyeok", meaning: "Calendar" },
        { korean: "창문", romanization: "changmun", meaning: "Window" },
        { korean: "문", romanization: "mun", meaning: "Door" },
        { korean: "가방/배낭", romanization: "gabang/baenang", meaning: "Bag" },
        { korean: "수첩", romanization: "sucheop", meaning: "Pocketbook" },
        { korean: "안경", romanization: "angyeong", meaning: "Eyeglasses" },
        { korean: "칼", romanization: "kal", meaning: "Knife/Cutter" },
        { korean: "가위", romanization: "gawi", meaning: "Scissors" },
        { korean: "젓가락", romanization: "jeotgarak", meaning: "Chopstick" },
        { korean: "숟가락", romanization: "sutgarak", meaning: "Spoon" },
        { korean: "수저", romanization: "sujeo", meaning: "Spoon and chopstick" },
        { korean: "계산기", romanization: "gyesangi", meaning: "Calculator" },
        { korean: "쓰레기통", romanization: "sseuregitong", meaning: "Garbage bin" },
        { korean: "건강보험증", romanization: "geongang bheomjeung", meaning: "Health insurance card" },
        { korean: "신분증", romanization: "sinbunjeung", meaning: "Resident card" },
        { korean: "신용카드", romanization: "sinyong kadeu", meaning: "Credit card" },
        { korean: "교통카드", romanization: "gyotong kadeu", meaning: "Transport card" },
        { korean: "학생증", romanization: "haksaengjeung", meaning: "School ID" },
        { korean: "사원증", romanization: "sawonjeung", meaning: "Company ID" },
        { korean: "운전면허증", romanization: "unjeon myeonheojeung", meaning: "Driver's license" },
        { korean: "신문", romanization: "sinmun", meaning: "Newspaper" },
        { korean: "돈", romanization: "don", meaning: "Money" },
        { korean: "카드", romanization: "kadeu", meaning: "Card" },
        { korean: "우표", romanization: "upyo", meaning: "Stamp" },
        { korean: "명함", romanization: "myeongham", meaning: "Calling card" },
        { korean: "여권", romanization: "yeogwon", meaning: "Passport" },
        { korean: "우산", romanization: "usan", meaning: "Umbrella" },
        { korean: "모자", romanization: "moja", meaning: "Hat/Cap" },
        { korean: "장갑", romanization: "janggap", meaning: "Gloves" },
        { korean: "바지", romanization: "baji", meaning: "Pants" },
        { korean: "치마", romanization: "chima", meaning: "Skirt" },
        { korean: "거울", romanization: "geoul", meaning: "Mirror" }
    ],

    "Objects 2": [
        { korean: "지도", romanization: "jido", meaning: "Map" },
        { korean: "사전", romanization: "sajeon", meaning: "Dictionary" },
        { korean: "열쇠", romanization: "yeolsoe", meaning: "Key" },
        { korean: "지폐", romanization: "jipye", meaning: "Paper money" },
        { korean: "영화표", romanization: "yeonghwapyo", meaning: "Movie ticket" },
        { korean: "영수증", romanization: "yeongsujeung", meaning: "Receipt" },
        { korean: "양말", romanization: "yangmal", meaning: "Socks" },
        { korean: "운동화", romanization: "undonghwa", meaning: "Running shoes" },
        { korean: "지갑", romanization: "jigap", meaning: "Wallet" },
        { korean: "옷/의류", romanization: "ot/uiryu", meaning: "Clothes" },
        { korean: "꽃", romanization: "kkot", meaning: "Flower" },
        { korean: "공", romanization: "gong", meaning: "Ball" },
        { korean: "고무장화", romanization: "gomu janghwa", meaning: "Rubber boots" },
        { korean: "고무장갑", romanization: "gomu janggap", meaning: "Rubber gloves" },
        { korean: "귀덮개", romanization: "gwideomgae", meaning: "Ear cover" },
        { korean: "가족사진", romanization: "gajok sajin", meaning: "Family picture" },
        { korean: "화장품", romanization: "hwajanpum", meaning: "Cosmetic products" },
        { korean: "빗", romanization: "bit", meaning: "Brush" },
        { korean: "헤어드라이어", romanization: "heeo deuraiyeo", meaning: "Hair dryer" },
        { korean: "베개", romanization: "begae", meaning: "Pillow" },
        { korean: "이불", romanization: "ibul", meaning: "Blanket" },
        { korean: "린스", romanization: "rinseu", meaning: "Conditioner" },
        { korean: "샴푸", romanization: "syampu", meaning: "Shampoo" },
        { korean: "비누", romanization: "binu", meaning: "Soap" },
        { korean: "칫솔", romanization: "chitsol", meaning: "Toothbrush" },
        { korean: "치약", romanization: "chiyak", meaning: "Toothpaste" },
        { korean: "수건", romanization: "sugeon", meaning: "Towel" },
        { korean: "면도기", romanization: "myeondogi", meaning: "Razor" },
        { korean: "휴지", romanization: "hyuji", meaning: "Toilet paper" },
        { korean: "컵", romanization: "keop", meaning: "Cup" },
        { korean: "의류", romanization: "uiryu", meaning: "Clothing" },
        { korean: "티셔츠", romanization: "tisyeocheu", meaning: "T-shirt" },
        { korean: "잠바", romanization: "jamba", meaning: "Jacket" },
        { korean: "구두/신발", romanization: "gudu/sinbal", meaning: "Shoes" },
        { korean: "슬리퍼/신발화", romanization: "seullipeo/sinbalhwa", meaning: "Slippers" },
        { korean: "장화", romanization: "janghwa", meaning: "Rain boots" },
        { korean: "양말", romanization: "yangmal", meaning: "Sacks" },
        { korean: "목도리", romanization: "mokdori", meaning: "Scarf" }
    ],

    // MODE OF TRANSPORTATION
    "Mode of Transportation": [
        { korean: "기차", romanization: "gicha", meaning: "Train" },
        { korean: "자전거", romanization: "jajeongeo", meaning: "Bicycle" },
        { korean: "비행기", romanization: "bihaenggi", meaning: "Airplane" },
        { korean: "지하철", romanization: "jihacheol", meaning: "Subway" },
        { korean: "자동차", romanization: "jadongcha", meaning: "Car" },
        { korean: "배", romanization: "bae", meaning: "Boat/Ship" },
        { korean: "마을 버스", romanization: "maeul beoseu", meaning: "Shuttle bus (in-town)" },
        { korean: "시내버스", romanization: "sinaebeoseu", meaning: "Intercity bus" },
        { korean: "시외/고속버스", romanization: "siwoe/gosokbeoseu", meaning: "Express bus" },
        { korean: "버스터미널", romanization: "beoseu teomineol", meaning: "Bus terminal" },
        { korean: "택시 승강장", romanization: "taeksi seunggangjiang", meaning: "Taxi stop" },
        { korean: "기차역", romanization: "gichayeok", meaning: "Train station" },
        { korean: "지하철역", romanization: "jihacheol yeok", meaning: "Subway station" }
    ],

    // ELECTRONIC APPLIANCES
    "Electronic Appliances": [
        { korean: "자동판매기/자판기", romanization: "jadong panmaegi/japangi", meaning: "Vending machine" },
        { korean: "자동인출기", romanization: "jadong inchulgi", meaning: "ATM machine" },
        { korean: "선풍기", romanization: "seonpunggi", meaning: "Electric fan" },
        { korean: "온도계", romanization: "ondogye", meaning: "Thermometer" },
        { korean: "청소기", romanization: "cheongsogi", meaning: "Vacuum cleaner" },
        { korean: "세탁기", romanization: "setakgi", meaning: "Washing machine" },
        { korean: "전화기", romanization: "jeonhwagi", meaning: "Telephone" },
        { korean: "냉장고", romanization: "naengjanggo", meaning: "Refrigerator" },
        { korean: "가습기", romanization: "gaseupgi", meaning: "Humidifier" },
        { korean: "휴대전화", romanization: "hyudae jeonhwa", meaning: "Cellphone" },
        { korean: "전자 레인지", romanization: "jeonja reinji", meaning: "Microwave" },
        { korean: "밥솥", romanization: "bapsot", meaning: "Rice cooker" },
        { korean: "사진기", romanization: "sajingi", meaning: "Camera" },
        { korean: "난로", romanization: "nallo", meaning: "Heater" },
        { korean: "다리미", romanization: "darimi", meaning: "Iron" },
        { korean: "환풍기", romanization: "hwanpunggi", meaning: "Ventilator" },
        { korean: "복사기", romanization: "boksagi", meaning: "Copier machine" }
    ],

    // FURNITURE
    "Furniture": [
        { korean: "가구", romanization: "gagu", meaning: "Furniture" },
        { korean: "서류함", romanization: "seoryuham", meaning: "Filing cabinet" },
        { korean: "보관함", romanization: "bogwanham", meaning: "Storage box/Locker" },
        { korean: "우체통", romanization: "uchetong", meaning: "Mailbox" },
        { korean: "옷장", romanization: "otjang", meaning: "Closet" },
        { korean: "책장/책꽂", romanization: "chaekjang/chaekkkot", meaning: "Bookshelf" },
        { korean: "침대", romanization: "chimdae", meaning: "Bed" },
        { korean: "의자", romanization: "uija", meaning: "Chair" },
        { korean: "서랍장", romanization: "seorapjang", meaning: "Drawer" },
        { korean: "책상", romanization: "chaeksang", meaning: "Study table" },
        { korean: "밥상", romanization: "bapsang", meaning: "Dining table" }
    ],

    // FRUIT AND FOOD
    "Fruit and Food": [
        { korean: "사과", romanization: "sagwa", meaning: "Apple" },
        { korean: "오렌지/귤", romanization: "orenji/gyul", meaning: "Orange" },
        { korean: "포도", romanization: "podo", meaning: "Grape" },
        { korean: "수박", romanization: "subak", meaning: "Watermelon" },
        { korean: "딸기", romanization: "ttalgi", meaning: "Strawberry" },
        { korean: "배", romanization: "bae", meaning: "Pear" },
        { korean: "물", romanization: "mul", meaning: "Water" },
        { korean: "주스", romanization: "juseu", meaning: "Juice" },
        { korean: "우유", romanization: "uyu", meaning: "Milk" },
        { korean: "빵", romanization: "ppang", meaning: "Bread" },
        { korean: "라면", romanization: "ramyeon", meaning: "Instant noodles" },
        { korean: "과자", romanization: "gwaja", meaning: "Snacks" },
        { korean: "아이스크림", romanization: "aiseukeurim", meaning: "Ice cream" },
        { korean: "음식", romanization: "eumsik", meaning: "Food" },
        { korean: "곡식", romanization: "goksik", meaning: "Grains" },
        { korean: "채소/야채", romanization: "chaeso/yachae", meaning: "Vegetables" },
        { korean: "반찬", romanization: "banchan", meaning: "Side dish" }
    ],

    // PLACES
    "Places": [
        { korean: "회사", romanization: "hoesa", meaning: "Workplace" },
        { korean: "사무실", romanization: "samusil", meaning: "Office" },
        { korean: "화장실", romanization: "hwajangsil", meaning: "Restroom" },
        { korean: "식당", romanization: "sikdang", meaning: "Restaurant" },
        { korean: "집/댁", romanization: "jip/daek", meaning: "House" },
        { korean: "기숙사", romanization: "gisuksa", meaning: "Dormitory" },
        { korean: "세탁소", romanization: "setakso", meaning: "Laundromat" },
        { korean: "미용실", romanization: "miyongsil", meaning: "Hair salon" },
        { korean: "시장", romanization: "sijang", meaning: "Market" },
        { korean: "마트", romanization: "mateu", meaning: "Mart" },
        { korean: "편의점", romanization: "pyeonuijeom", meaning: "Convenient store" },
        { korean: "슈퍼마켓", romanization: "syupeo maket", meaning: "Supermarket" },
        { korean: "공중전화", romanization: "gongjung jeonhwa", meaning: "Phonebooth" },
        { korean: "소방서", romanization: "sobangso", meaning: "Fire station" },
        { korean: "공장", romanization: "gongjang", meaning: "Factory" },
        { korean: "경찰서", romanization: "gyeongchalso", meaning: "Police station" },
        { korean: "회사", romanization: "hoesa", meaning: "Company" },
        { korean: "책방/책 가게/서점", romanization: "chaekbang/chaek gage/seojeom", meaning: "Book store" },
        { korean: "도서관", romanization: "doseogwan", meaning: "Library" },
        { korean: "버스 정류장", romanization: "beoseu jeongnyujang", meaning: "Bus station" },
        { korean: "주차장", romanization: "juchajang", meaning: "Parking lot" },
        { korean: "건물", romanization: "geonmul", meaning: "Building" },
        { korean: "농장", romanization: "nongjang", meaning: "Farm" },
        { korean: "병원", romanization: "byeongwon", meaning: "Hospital" },
        { korean: "우체국", romanization: "ucheguk", meaning: "Post office" },
        { korean: "약국", romanization: "yakguk", meaning: "Pharmacy" },
        { korean: "영화관", romanization: "yeonghwagwan", meaning: "Movie theater" },
        { korean: "은행", romanization: "eunhaeng", meaning: "Bank" },
        { korean: "학교", romanization: "hakgyo", meaning: "School" },
        { korean: "공원", romanization: "gongwon", meaning: "Park" },
        { korean: "부엌", romanization: "bueok", meaning: "Kitchen" },
        { korean: "돼지우리", romanization: "dwaejiuri", meaning: "Piggery" },
        { korean: "양계장", romanization: "yanggyejang", meaning: "Chicken farm" },
        { korean: "축사", romanization: "chuksa", meaning: "Poultry/Barn" },
        { korean: "교실", romanization: "gyosil", meaning: "Classroom" },
        { korean: "공항", romanization: "gonghang", meaning: "Airport" },
        { korean: "고향", romanization: "gohyang", meaning: "Hometown" },
        { korean: "노래방", romanization: "noraebang", meaning: "Karaoke" },
        { korean: "PC 방", romanization: "PC bang", meaning: "Internet cafe" },
        { korean: "지하", romanization: "jiha", meaning: "Basement" },
        { korean: "계단", romanization: "gyedan", meaning: "Stairs" }
    ],

    "Government and Public Offices": [
        { korean: "도청", romanization: "docheong", meaning: "Provincial Government Building" },
        { korean: "시청", romanization: "sicheong", meaning: "City Hall" },
        { korean: "구청", romanization: "gucheong", meaning: "Borough Office" },
        { korean: "출입국 관리 사무소", romanization: "churipguk gwalli samusso", meaning: "Immigration Office" },
        { korean: "보건소", romanization: "bogeonso", meaning: "(Public) Health Center" },
        { korean: "주민센터", romanization: "jumin senteo", meaning: "Community Service Center" }
    ],

    "Occupations": [
        { korean: "선생님/교사/교수", romanization: "seonsaengnim/gyosa/gyosu", meaning: "Teacher" },
        { korean: "회사원", romanization: "hoesawon", meaning: "Business Person" },
        { korean: "주부", romanization: "jubu", meaning: "Homemaker" },
        { korean: "경찰관", romanization: "gyeongchalgwan", meaning: "Police Officer" },
        { korean: "군인", romanization: "gunin", meaning: "Soldier" },
        { korean: "소방관", romanization: "sobang-gwan", meaning: "Fire Fighter" },
        { korean: "공무원", romanization: "gongmuwon", meaning: "Public Official" },
        { korean: "점원", romanization: "jeomwon", meaning: "Clerk" },
        { korean: "의사", romanization: "uisa", meaning: "Doctor" },
        { korean: "간호사", romanization: "ganhosa", meaning: "Nurse" },
        { korean: "요리사", romanization: "yorisa", meaning: "Cook" },
        { korean: "운전기사", romanization: "unjeon gisa", meaning: "Driver" },
        { korean: "기술자", romanization: "gisulsa", meaning: "Technician" },
        { korean: "목수", romanization: "moksu", meaning: "Carpenter" },
        { korean: "농부", romanization: "nongbu", meaning: "Farmer" },
        { korean: "어부", romanization: "eobu", meaning: "Fisherman" },
        { korean: "미용사", romanization: "miyongsa", meaning: "Hairdresser" }
    ],

    "Country": [
        { korean: "한국", romanization: "hanguk", meaning: "The Republic Of Korea" },
        { korean: "네팔", romanization: "nepal", meaning: "Nepal" },
        { korean: "동티모르", romanization: "dongtimoleu", meaning: "East Timor" },
        { korean: "몽골", romanization: "monggol", meaning: "Mongolia" },
        { korean: "미얀마", romanization: "miyanma", meaning: "Myanmar" },
        { korean: "방글라데시", romanization: "banggeulladesyi", meaning: "Bangladesh" },
        { korean: "베트남", romanization: "beteunam", meaning: "Vietnam" },
        { korean: "스리랑카", romanization: "seurirangka", meaning: "Sri Lanka" },
        { korean: "우즈베키스탄", romanization: "ujeubek'iseuton", meaning: "Uzbekistan" },
        { korean: "인도네시아", romanization: "indonesia", meaning: "Indonesia" },
        { korean: "중국", romanization: "jungguk", meaning: "China" },
        { korean: "캄보디아", romanization: "kambodia", meaning: "Cambodia" },
        { korean: "키르기스스탄", romanization: "kireugisuseutan", meaning: "Kyrgyzstan" },
        { korean: "태국", romanization: "taeguk", meaning: "Thailand" },
        { korean: "파키스탄", romanization: "pakistan", meaning: "Pakistan" },
        { korean: "필리핀", romanization: "pillipin", meaning: "Philippines" }
    ],

    "Family": [
        { korean: "있다", romanization: "itda", meaning: "To Have" },
        { korean: "없다", romanization: "eopda", meaning: "To Not Have" },
        { korean: "많다", romanization: "manta", meaning: "To Be Many" },
        { korean: "살다", romanization: "salda", meaning: "To Live" },
        { korean: "할아버지", romanization: "harabeoji", meaning: "Grandfather" },
        { korean: "할머니", romanization: "halmeoni", meaning: "Grandmother" },
        { korean: "아버지", romanization: "abeoji", meaning: "Father" },
        { korean: "어머니", romanization: "eomeoni", meaning: "Mother" },
        { korean: "형", romanization: "hyeong", meaning: "Older Brother (Boy)" },
        { korean: "오빠", romanization: "oppa", meaning: "Older Brother (Girl)" },
        { korean: "누나", romanization: "nuna", meaning: "Older Sister (Boy)" },
        { korean: "언니", romanization: "eonni", meaning: "Older Sister (Girl)" },
        { korean: "아들", romanization: "adeul", meaning: "Son" },
        { korean: "딸", romanization: "ttal", meaning: "Daughter" },
        { korean: "부인", romanization: "buin", meaning: "Wife" },
        { korean: "남편", romanization: "nampyeon", meaning: "Husband" },
        { korean: "여동생", romanization: "yeodongsaeng", meaning: "Younger Sister" },
        { korean: "남동생", romanization: "namdongsaeng", meaning: "Younger Brother" },
        { korean: "형제/아우", romanization: "hyeongje/au", meaning: "Sibling" }
    ],

    "Greetings": [
        { korean: "안녕하세요", romanization: "annyeong haseyo", meaning: "General Greeting" },
        { korean: "만나서 반갑습니다", romanization: "mannaseo bangapseumnida", meaning: "Nice To Meet You" },
        { korean: "만나서 반갑습니다", romanization: "mannaseo bangapseumnida", meaning: "Nice To Meet You Too" },
        { korean: "안녕히 계세요", romanization: "annyeonghi gyeseyo", meaning: "Goodbye (Person Leaving)" },
        { korean: "안녕히 가세요", romanization: "annyeonghi gaseyo", meaning: "Goodbye (Person Staying)" },
        { korean: "감사합니다", romanization: "gamsahamnida", meaning: "Thank You" },
        { korean: "아니에요", romanization: "anieyo", meaning: "You're Welcome" },
        { korean: "죄송합니다", romanization: "joesonghamnida", meaning: "I'm Sorry" },
        { korean: "괜찮아요", romanization: "gwaenchanhayo", meaning: "It's Ok" },
        { korean: "주말 잘 보내세요", romanization: "jumal jal bonaeseyo", meaning: "Have A Great Weekend" },
        { korean: "안녕히 주무세요", romanization: "annyeonghi jumuseyo", meaning: "Good Night!" },
        { korean: "잘 자요", romanization: "jal jayo", meaning: "Good Night!" },
        { korean: "안녕히 주무셨어요?", romanization: "annyeonghi jumusyeosseoyo?", meaning: "Good Morning?" },
        { korean: "잘 먹겠습니다", romanization: "jal meokgetseumnida", meaning: "Thank You For The Meal" },
        { korean: "맛이 드세요", romanization: "masi deuseyo", meaning: "Enjoy Your Meal!" },
        { korean: "잘 먹었습니다", romanization: "jal meogeotsseumnida", meaning: "I Enjoyed The Meal" },
        { korean: "주말 잘 보내세요", romanization: "jumal jal bonaeseyo", meaning: "Have A Great Weekend" },
        { korean: "네, 주말 잘 보내세요", romanization: "ne, jumal jal bonaeseyo", meaning: "Have A Nice Weekend!" },
        { korean: "축하합니다", romanization: "chukhahamnida", meaning: "Congratulations!" },
        { korean: "감사합니다", romanization: "gamsahamnida", meaning: "Thank You" }
    ],

    "Daily Routine": [
        { korean: "일어나다", romanization: "ireonada", meaning: "to get up" },
        { korean: "씻다", romanization: "ssitda", meaning: "to wash" },
        { korean: "아침을 먹다", romanization: "achimeul meokda", meaning: "to have breakfast" },
        { korean: "회사에 가다", romanization: "hoesae gada", meaning: "to go to work" },
        { korean: "일하다", romanization: "ilhada", meaning: "to work" },
        { korean: "쉬다", romanization: "swida", meaning: "to rest" },
        { korean: "점심을 먹다", romanization: "jeomshimeul meokda", meaning: "to have lunch" },
        { korean: "집에 오다", romanization: "jibe oda", meaning: "to come home" },
        { korean: "장을 보다", romanization: "jangeul boda", meaning: "to go grocery shopping" },
        { korean: "요리하다", romanization: "yorihada", meaning: "to cook" },
        { korean: "저녁을 먹다", romanization: "jeonyeogeul meokda", meaning: "to have dinner" },
        { korean: "커피를 마시다", romanization: "keopireul masida", meaning: "to drink coffee" },
        { korean: "운동하다", romanization: "undonghada", meaning: "to workout" },
        { korean: "노래하다", romanization: "noraehada", meaning: "to sing" },
        { korean: "게임하다", romanization: "geimhada", meaning: "to play" },
        { korean: "산책하다", romanization: "sanchaekhada", meaning: "to take a walk" },
        { korean: "소핑하다", romanization: "sopinghada", meaning: "to go shopping" },
        { korean: "책을 읽다", romanization: "chaegeul ikda", meaning: "to read" },
        { korean: "영화를 보다", romanization: "yeonghwareul boda", meaning: "to see a movie" },
        { korean: "음식을 만들다", romanization: "eumsigeul mandeulda", meaning: "to cook" },
        { korean: "한국어를 공부하다", romanization: "hangugeoreul gongbuhada", meaning: "to study Korean" },
        { korean: "친구를 만나다", romanization: "chingureul mannada", meaning: "to meet a friend" },
        { korean: "텔레비전을 보다", romanization: "tellebijyoneul boda", meaning: "to watch television" },
        { korean: "전화하다", romanization: "jeonhwahada", meaning: "to call" },
        { korean: "자다", romanization: "jada", meaning: "to sleep" }
    ],

    "Range of Hours": [
        { korean: "지금", romanization: "jigeum", meaning: "now" },
        { korean: "오늘", romanization: "oneul", meaning: "today" },
        { korean: "내일", romanization: "naeil", meaning: "tomorrow" },
        { korean: "오전", romanization: "ojeon", meaning: "a.m./morning" },
        { korean: "오후", romanization: "ohu", meaning: "p.m./afternoon" },
        { korean: "낮", romanization: "nat", meaning: "day time" },
        { korean: "밤", romanization: "bam", meaning: "night time" },
        { korean: "새벽", romanization: "saebyeok", meaning: "dawn" },
        { korean: "아침", romanization: "achim", meaning: "morning" },
        { korean: "점심", romanization: "jeomsim", meaning: "afternoon" },
        { korean: "저녁", romanization: "jeonyeok", meaning: "evening" },
        { korean: "지난달", romanization: "jinandal", meaning: "last month" },
        { korean: "이번 달", romanization: "ibeon dal", meaning: "this month" },
        { korean: "다음 달", romanization: "daeum dal", meaning: "next month" },
        { korean: "어제", romanization: "eoje", meaning: "yesterday" },
        { korean: "지난주", romanization: "jinanju", meaning: "last week" },
        { korean: "이번 주", romanization: "ibeon ju", meaning: "this week" },
        { korean: "다음 주", romanization: "daeum ju", meaning: "next week" },
        { korean: "주중/평일", romanization: "jujung/pyeongil", meaning: "weekdays" },
        { korean: "주말", romanization: "jumal", meaning: "weekends" },
        { korean: "작년", romanization: "jangnyeon", meaning: "last year" },
        { korean: "올해", romanization: "olhae", meaning: "this year" },
        { korean: "내년", romanization: "naenyeon", meaning: "next year" }
    ],

    "Looks and Personality": [
        { korean: "예쁘다", romanization: "yeppeuda", meaning: "pretty" },
        { korean: "멋있다", romanization: "meositda", meaning: "cool" },
        { korean: "키가 크다", romanization: "kiga keuda", meaning: "tall" },
        { korean: "키가 작다", romanization: "kiga jakda", meaning: "short" },
        { korean: "날씬하다", romanization: "nalssinhada", meaning: "skinny" },
        { korean: "뚱뚱하다", romanization: "ttungttunghada", meaning: "fat" },
        { korean: "재미있다", romanization: "jaemiitda", meaning: "funny" },
        { korean: "친절하다", romanization: "chinjeolhada", meaning: "kind" },
        { korean: "똑똑하다", romanization: "ttokttokada", meaning: "smart" },
        { korean: "활발하다", romanization: "hwalbalhada", meaning: "outgoing" },
        { korean: "암전하다", romanization: "amjeonhada", meaning: "introvert" },
        { korean: "부지런하다", romanization: "bujireonhada", meaning: "diligent" }
    ],

    "Money and Purchasing Goods": [
        { korean: "돈/현금", romanization: "don/hyeongeum", meaning: "money" },
        { korean: "동전", romanization: "dongjeon", meaning: "coin" },
        { korean: "지폐", romanization: "jipye", meaning: "paper money" },
        { korean: "신용카드", romanization: "sinyong kadeu", meaning: "credit card" },
        { korean: "값/가격", romanization: "gap/gagyeok", meaning: "price" },
        { korean: "싸다", romanization: "ssada", meaning: "cheap" },
        { korean: "비싸다", romanization: "bissada", meaning: "expensive" },
        { korean: "(값을) 깎다", romanization: "(gapseul) kkakda", meaning: "to bargain" },
        { korean: "넣다", romanization: "neota", meaning: "to put in" },
        { korean: "싸다/포장하다", romanization: "ssada/pojanghada", meaning: "to wrap up" },
        { korean: "바꾸다/교환하다", romanization: "bakkuda/gyohwanhada", meaning: "to exchange" },
        { korean: "환불하다", romanization: "hwanbulhada", meaning: "to refund" }
    ],

    "Locomotive Verbs": [
        { korean: "내려가다", romanization: "naeryeogada", meaning: "to go down" },
        { korean: "내려오다", romanization: "naeryeooda", meaning: "to come down" },
        { korean: "올라가다", romanization: "ollagada", meaning: "to go up" },
        { korean: "올라오다", romanization: "ollaoda", meaning: "to come up" },
        { korean: "나가다", romanization: "nagada", meaning: "to go out" },
        { korean: "나오다", romanization: "naoda", meaning: "to come out" },
        { korean: "들어가다", romanization: "deureogada", meaning: "to enter/go in" },
        { korean: "들어오다", romanization: "deureooda", meaning: "to come in" },
        { korean: "돌아가다", romanization: "doragada", meaning: "to return/go back" },
        { korean: "돌아오다", romanization: "doraoda", meaning: "to return/comeback" }
    ],

    "Signs": [
        { korean: "앞으로 가세요", romanization: "apeuro gaseyo", meaning: "To Go Forward" },
        { korean: "뒤로 가세요", romanization: "dwiro gaseyo", meaning: "To Go Backward" },
        { korean: "오른쪽으로 가세요", romanization: "oreunjjogeuro gaseyo", meaning: "To Go Right" },
        { korean: "왼쪽으로 가세요", romanization: "oenjjogeuro gaseyo", meaning: "To Go Left" },
        { korean: "위로 올라가세요", romanization: "wiro ollagaseyo", meaning: "To Go Up" },
        { korean: "아래로 내려가세요", romanization: "araero naeryeogaseyo", meaning: "To Go Down" }
    ],

    "Locations and Directions": [
        { korean: "위", romanization: "wi", meaning: "up" },
        { korean: "아래", romanization: "arae", meaning: "down" },
        { korean: "앞", romanization: "ap", meaning: "front" },
        { korean: "뒤", romanization: "dwi", meaning: "back" },
        { korean: "안", romanization: "an", meaning: "inside" },
        { korean: "밖", romanization: "bak", meaning: "outside" },
        { korean: "오른쪽", romanization: "oreunjjok", meaning: "right" },
        { korean: "왼쪽", romanization: "oenjjok", meaning: "left" },
        { korean: "건너편/맞은편", romanization: "geonneopyeon/majeunpyeon", meaning: "across the street" },
        { korean: "옆", romanization: "yeop", meaning: "next to" },
        { korean: "사이", romanization: "sai", meaning: "between" },
        { korean: "가운데/중간", romanization: "gaunde/junggan", meaning: "in the middle" }
    ],

    "Streets": [
        { korean: "육교", romanization: "yukgyo", meaning: "Pedestrian overpass" },
        { korean: "이정표", romanization: "ijeongpyo", meaning: "road signs" },
        { korean: "신호등", romanization: "sinhodeung", meaning: "traffic lights" },
        { korean: "횡단보도", romanization: "hoengdanbodo", meaning: "crossway" },
        { korean: "길", romanization: "gil", meaning: "road/streets" },
        { korean: "도로", romanization: "doro", meaning: "road" },
        { korean: "골목", romanization: "golmok", meaning: "alley" }
    ],

    "Stative Verb 1": [
        { korean: "시간(이) 있다", romanization: "sigan(i) itda", meaning: "to have time" },
        { korean: "시간(이) 없다", romanization: "sigan(i) eopda", meaning: "not to have time" },
        { korean: "약속(이) 있다", romanization: "yaksok(i) itda", meaning: "to have an appointment" },
        { korean: "약속(이) 없다", romanization: "yaksok(i) eopda", meaning: "not to have an appointment" },
        { korean: "일이 많다", romanization: "iri manta", meaning: "to have a lot of work" },
        { korean: "일이 적다", romanization: "iri jeokda", meaning: "not to have much work" },
        { korean: "바쁘다", romanization: "bappeuda", meaning: "to be busy" },
        { korean: "한가하다", romanization: "hangahada", meaning: "to be free" },
        { korean: "재미있다", romanization: "jaemiitda", meaning: "to be interesting/fun" },
        { korean: "재미없다", romanization: "jaemieopda", meaning: "to be not interesting/boring" },
        { korean: "좋다", romanization: "jota", meaning: "nice" },
        { korean: "괜찮다", romanization: "gwaenchanta", meaning: "fine" }
    ],

    "Stative Verb 2": [
        { korean: "빠르다(이르다)", romanization: "ppareuda(ireuda)", meaning: "early" },
        { korean: "늦다", romanization: "neutda", meaning: "late" },
        { korean: "가깝다", romanization: "gakkapda", meaning: "close" },
        { korean: "멀다", romanization: "meolda", meaning: "far" },
        { korean: "같다", romanization: "gatda", meaning: "same" },
        { korean: "다르다", romanization: "dareuda", meaning: "different" },
        { korean: "간단하다", romanization: "gandanhada", meaning: "simple" },
        { korean: "복잡하다", romanization: "bokjapada", meaning: "complicated" },
        { korean: "편하다", romanization: "pyeonhada", meaning: "comfortable" },
        { korean: "불편하다", romanization: "bulpyeonhada", meaning: "uncomfortable" },
        { korean: "가능하다", romanization: "ganeunghada", meaning: "possible" },
        { korean: "불가능하다", romanization: "bulganeunghada", meaning: "impossible" }
    ],

    "Restaurant": [
        { korean: "자리가 있다", romanization: "jariga itda", meaning: "seats are available" },
        { korean: "자리가 없다", romanization: "jariga eopda", meaning: "seats are not available" },
        { korean: "메뉴판", romanization: "menyupan", meaning: "menu book" },
        { korean: "메뉴", romanization: "menyu", meaning: "menu" },
        { korean: "밥", romanization: "bap", meaning: "rice" },
        { korean: "반찬", romanization: "banchan", meaning: "side dishes" },
        { korean: "숟가락", romanization: "sutgarak", meaning: "spoon" },
        { korean: "젓가락", romanization: "jeotgarak", meaning: "chopsticks" },
        { korean: "앉다", romanization: "anda", meaning: "to seat" },
        { korean: "고르다", romanization: "goreuda", meaning: "to pick" },
        { korean: "시키다(주문하다)", romanization: "sikida(jumunhada)", meaning: "to order" },
        { korean: "배달하다", romanization: "baedalhada", meaning: "to deliver" }
    ],

    "Taste of Foods": [
        { korean: "맛있다", romanization: "masitda", meaning: "delicious" },
        { korean: "맛없다", romanization: "maseopda", meaning: "not tasty" },
        { korean: "맵다", romanization: "maepda", meaning: "spicy" },
        { korean: "달다", romanization: "dalda", meaning: "sweet" },
        { korean: "짜다", romanization: "jjada", meaning: "salty" },
        { korean: "싱겁다", romanization: "singgeopda", meaning: "bland" },
        { korean: "쓰다", romanization: "sseuda", meaning: "bitter" },
        { korean: "시다", romanization: "sida", meaning: "sour" }
    ],

    "Weather and Seasons": [
        { korean: "비가 오다", romanization: "biga oda", meaning: "to rain" },
        { korean: "눈이 오다", romanization: "nuni oda", meaning: "to snow" },
        { korean: "바람이 불다", romanization: "barami bulda", meaning: "to be windy" },
        { korean: "그치다", romanization: "geuchida", meaning: "to stop" },
        { korean: "날씨가 좋다", romanization: "nalssiga jota", meaning: "the weather is good" },
        { korean: "날씨가 나쁘다", romanization: "nalssiga nappeuda", meaning: "the weather is bad" },
        { korean: "맑다", romanization: "malkda", meaning: "clear" },
        { korean: "흐리다", romanization: "heurida", meaning: "cloudy" },
        { korean: "따뜻하다", romanization: "ttatteuthada", meaning: "warm" },
        { korean: "덥다", romanization: "deopda", meaning: "hot" },
        { korean: "시원하다", romanization: "siwonhada", meaning: "cool" },
        { korean: "춥다", romanization: "chupda", meaning: "cold" },
        { korean: "봄", romanization: "bom", meaning: "spring" },
        { korean: "여름", romanization: "yeoreum", meaning: "summer" },
        { korean: "가을", romanization: "gaeul", meaning: "fall/autumn" },
        { korean: "겨울", romanization: "gyeoul", meaning: "winter" }
    ],

    "Adverbs": [
        { korean: "정말/진짜", romanization: "jeongmal/jinjja", meaning: "Really/truly" },
        { korean: "참", romanization: "cham", meaning: "really" },
        { korean: "아주", romanization: "aju", meaning: "very" },
        { korean: "너무", romanization: "neomu", meaning: "too much" },
        { korean: "제일/가장", romanization: "jeil/gajang", meaning: "the most/the best" },
        { korean: "특히", romanization: "teuki", meaning: "especially" },
        { korean: "많이", romanization: "mani", meaning: "many/much/a lot" },
        { korean: "조금", romanization: "jogeum", meaning: "few/little" }
    ],

    "Feelings and Moods": [
        { korean: "기분이 좋다", romanization: "gibuni jota", meaning: "to feel good" },
        { korean: "기분이 나쁘다", romanization: "gibuni nappeuda", meaning: "to feel bad" },
        { korean: "기쁘다", romanization: "gippeuda", meaning: "please" },
        { korean: "슬프다", romanization: "seulpeuda", meaning: "sad" },
        { korean: "즐겁다", romanization: "jeulgeopda", meaning: "pleasant" },
        { korean: "신나다", romanization: "sinnada", meaning: "excited" },
        { korean: "상쾌하다", romanization: "sangkwaehada", meaning: "to feel refreshed" },
        { korean: "행복하다", romanization: "haengbokhada", meaning: "happy" },
        { korean: "피곤하다", romanization: "pigonhada", meaning: "tired" },
        { korean: "졸리다", romanization: "jollida", meaning: "sleepy" },
        { korean: "외롭다", romanization: "oeropda", meaning: "lonely" },
        { korean: "우울하다", romanization: "uulhada", meaning: "depressed" }
    ],

    "Adverbs of Frequency": [
        { korean: "항상/늘", romanization: "hangsang/neul", meaning: "Always" },
        { korean: "자주", romanization: "jaju", meaning: "usually" },
        { korean: "가끔", romanization: "gakkeum", meaning: "occasionally" }
    ],

    "Hobbies": [
        { korean: "독서하다", romanization: "dokseo-hada", meaning: "to read" },
        { korean: "낚시하다", romanization: "naksi-hada", meaning: "to go fishing" },
        { korean: "여행하다", romanization: "yeohaeng-hada", meaning: "to travel" },
        { korean: "등산하다", romanization: "deungsan-hada", meaning: "to hiking" },
        { korean: "사진을 찍다", romanization: "sajineul jjikda", meaning: "to take pictures" },
        { korean: "외국어를 공부하다", romanization: "oegugeoreul gongbu-hada", meaning: "to study foreign language" },
        { korean: "음악회에 가다", romanization: "eumakhoee gada", meaning: "to go for a concert" },
        { korean: "운동 경기를 보다", romanization: "undong gyeongireul boda", meaning: "to watch sports games" },
        { korean: "음악을 듣다", romanization: "eumageul deutda", meaning: "to listen to music" },
        { korean: "기타를 치다", romanization: "gitareul chida", meaning: "to play the guitar" },
        { korean: "피아노를 치다", romanization: "pianoreul chida", meaning: "to play the piano" },
        { korean: "춤을 추다", romanization: "chumeul chuda", meaning: "to dance" }
    ],

    "Clubs for People with Shared Interests": [
        { korean: "축구 동호회", romanization: "chukgu dongho-hoe", meaning: "soccer club" },
        { korean: "등산 동호회", romanization: "deungsan dongho-hoe", meaning: "hiking club" },
        { korean: "사진 동호회", romanization: "sajin dongho-hoe", meaning: "photography club" },
        { korean: "요리 동호회", romanization: "yori dongho-hoe", meaning: "cooking club" }
    ],

    "Sports": [
        { korean: "축구하다", romanization: "chukgu-hada", meaning: "to play soccer" },
        { korean: "농구하다", romanization: "nonggu-hada", meaning: "to play basketball" },
        { korean: "야구하다", romanization: "yagu-hada", meaning: "to play baseball" },
        { korean: "수영하다", romanization: "suyeong-hada", meaning: "to swim" },
        { korean: "테니스 치다", romanization: "teniseu chida", meaning: "to play tennis" },
        { korean: "배드민턴 치다", romanization: "baedeu-minteon chida", meaning: "to play badminton" },
        { korean: "볼링 치다", romanization: "bolling chida", meaning: "to play bowling" },
        { korean: "골프 치다", romanization: "golpeu chida", meaning: "to play golf" },
        { korean: "스케이트 타다", romanization: "seukeiteuta-da", meaning: "to skate" },
        { korean: "스키 타다", romanization: "seuki ta-da", meaning: "to ski" },
        { korean: "자전거를 타다", romanization: "jajeongeo-reul ta-da", meaning: "to bike" }
    ],

    // NEW NUMBER PRACTICE CATEGORIES
    "Numbers Practice - Prices (Sino-Korean)": [],
    "Numbers Practice - Dates (Sino-Korean)": [],
    "Numbers Practice - Native Korean (1-20)": [],
    "Numbers Practice - Phone Numbers": [],
    "Telling Time (12hr)": [],

    "Counter Units (Native)": [
        { korean: "동", romanization: "dong", meaning: "block of buildings/houses" },
        { korean: "번/회", romanization: "beon/hwe", meaning: "no. of action done" },
        { korean: "정", romanization: "jeong", meaning: "no. of pieces of medicine" },
        { korean: "공기", romanization: "gonggi", meaning: "rice in a bowl" },
        { korean: "그릇", romanization: "geureut", meaning: "dish serve in bowl" },
        { korean: "접시", romanization: "jeopsi", meaning: "no. of dish serve in plate" },
        { korean: "조각", romanization: "jogak", meaning: "slices of food" },
        { korean: "가지", romanization: "gaji", meaning: "categories, kinds, sorts, groups, ways" },
        { korean: "통", romanization: "tong", meaning: "big round fruits / no. of phone calls/ emails/ letters / large round container" },
        { korean: "묶음", romanization: "mukeum", meaning: "bundle/package" },
        { korean: "포기", romanization: "pogi", meaning: "plants from roots" },
        { korean: "줄", romanization: "jul", meaning: "things arranged in lines" },
        { korean: "판", romanization: "pan", meaning: "dish serve in plate" },
        { korean: "바구니", romanization: "baguni", meaning: "basket of items" },
        { korean: "장", romanization: "jang", meaning: "thin/flat objects" },
        { korean: "송이", romanization: "songi", meaning: "bunches/stems" },
        { korean: "척", romanization: "cheok", meaning: "ships" },
        { korean: "개", romanization: "gae", meaning: "general items" },
        { korean: "갑", romanization: "gap", meaning: "handful of box" },
        { korean: "상자", romanization: "sangja", meaning: "no. of large box" },
        { korean: "봉지", romanization: "bongji", meaning: "bags of small things" },
        { korean: "포대", romanization: "podae", meaning: "sacks of items" },
        { korean: "잔", romanization: "jan", meaning: "no. of cups/glasses" },
        { korean: "병", romanization: "byeong", meaning: "no. of bottles" },
        { korean: "권", romanization: "gwon", meaning: "binded things/books" },
        { korean: "잎", romanization: "ip", meaning: "no. of leaves/petals" },
        { korean: "그루", romanization: "geuru", meaning: "no. of trees" },
        { korean: "마리", romanization: "mari", meaning: "no. of animals" },
        { korean: "채", romanization: "chae", meaning: "units of houses" },
        { korean: "살", romanization: "sal", meaning: "Age (years old)" },
        { korean: "분/명/사람", 
        romanization: "bun/myeong/saram", 
        meaning: "collective of people - 분 (honorific/polite for guests, elders), 명 (general/neutral for counting people), 사람 (natural/casual, also means 'person' or nationality)" },
        { korean: "시간", romanization: "sigan", meaning: "duration of time" },
        { korean: "시", romanization: "si", meaning: "no. of hours" },
        { korean: "달", romanization: "dal", meaning: "duration of months" },
        { korean: "벌", romanization: "beol", meaning: "pair of clothes / set of clothes" },
        { korean: "켤레", romanization: "kyeollae", meaning: "pair of things that wear on feet/hands" },
        { korean: "쌍", romanization: "ssang", meaning: "pair of animals, people and some special object" },
        { korean: "대", romanization: "dae", meaning: "machines/appliances/vehicles/musical instruments" },
        { korean: "자루", romanization: "jaru", meaning: "long handled things/tools" }
    ],

    "Counter Units (Sino)": [
        { korean: "번", romanization: "beon", meaning: "number" },
        { korean: "호", romanization: "ho", meaning: "no. of house/rooms" },
        { korean: "세", romanization: "se", meaning: "age" },
        { korean: "년", romanization: "nyeon", meaning: "years and duration" },
        { korean: "월", romanization: "wol", meaning: "months of the year" },
        { korean: "일", romanization: "il", meaning: "dates and days" },
        { korean: "박", romanization: "bak", meaning: "number of nights" },
        { korean: "개월", romanization: "gaewol", meaning: "duration of months" },
        { korean: "주", romanization: "ju", meaning: "number of weeks" },
        { korean: "분", romanization: "bun", meaning: "no. of minutes" },
        { korean: "초", romanization: "cho", meaning: "number of seconds" },
        { korean: "인분", romanization: "inbun", meaning: "portions of food" },
        { korean: "층", romanization: "cheung", meaning: "no. of floors" },
        { korean: "원", romanization: "won", meaning: "korean currency" }
    ]
};