// ALL FLASHCARD DATA - EPS TOPIK BOOK 1 AND 2
// This object contains all the Korean words organized by category

const flashcardData = {
    // ANIMALS
    "Animals": [
        { korean: "개", romanization: "gae", meaning: "Dog" },
        { korean: "강아지", romanization: "gangaji", meaning: "Puppy" },
        { korean: "고양이", romanization: "goyangi", meaning: "Cat" },
        { korean: "토끼", romanization: "tokki", meaning: "Rabbit" },
        { korean: "쥐", romanization: "jwi", meaning: "Mouse" },
        { korean: "새", romanization: "sae", meaning: "Bird" },
        { korean: "개구리", romanization: "gaeguri", meaning: "Frog" },
        { korean: "뱀", romanization: "baem", meaning: "Snake" },
        { korean: "까치", romanization: "kkachi", meaning: "Magpie" },
        { korean: "귀뚜라미", romanization: "gwittulami", meaning: "Cricket" }
    ],

    "Animal Farm": [
        { korean: "닭", romanization: "dak", meaning: "Chicken" },
        { korean: "소", romanization: "so", meaning: "Cow" },
        { korean: "오리", romanization: "ori", meaning: "Duck" },
        { korean: "물고기", romanization: "mulgogi", meaning: "Fish" },
        { korean: "염소", romanization: "yeomso", meaning: "Goat" },
        { korean: "말", romanization: "mal", meaning: "Horse" },
        { korean: "돼지", romanization: "dwaeji", meaning: "Pig" },
        { korean: "양", romanization: "yang", meaning: "Sheep" },
        { korean: "황소", romanization: "hwangso", meaning: "Ox" }
    ],

    "Wild Animals": [
        { korean: "호랑이", romanization: "horangi", meaning: "Tiger" },
        { korean: "사자", romanization: "saja", meaning: "Lion" },
        { korean: "여우", romanization: "yeou", meaning: "Fox" },
        { korean: "코끼리", romanization: "kokkiri", meaning: "Elephant" },
        { korean: "원숭이", romanization: "wonsungi", meaning: "Monkey" },
        { korean: "곰", romanization: "gom", meaning: "Bear" },
        { korean: "기린", romanization: "girin", meaning: "Giraffe" },
        { korean: "타조", romanization: "tajo", meaning: "Ostrich" }
    ],

    // OBJECTS
    "Objects": [
        { korean: "칠판", romanization: "chilpan", meaning: "Whiteboard/Blackboard" },
        { korean: "책", romanization: "chaek", meaning: "Book" },
        { korean: "공책", romanization: "gongchaek", meaning: "Notebook" },
        { korean: "연필", romanization: "yeonpil", meaning: "Pencil" },
        { korean: "볼펜", romanization: "bolpen", meaning: "Ball pen" },
        { korean: "지우개", romanization: "jiugae", meaning: "Eraser" },
        { korean: "필통", romanization: "piltong", meaning: "Pencil case" },
        { korean: "시계", romanization: "sigye", meaning: "Clock" },
        { korean: "달력", romanization: "dallyeok", meaning: "Calendar" },
        { korean: "창문", romanization: "changmun", meaning: "Window" },
        { korean: "문", romanization: "mun", meaning: "Door" },
        { korean: "가방/배낭", romanization: "gabang/baenang", meaning: "Bag" },
        { korean: "수첩", romanization: "sucheop", meaning: "Pocketbook" },
        { korean: "안경", romanization: "angyeong", meaning: "Eyeglasses" },
        { korean: "칼", romanization: "kal", meaning: "Knife/Cutter" },
        { korean: "가위", romanization: "gawi", meaning: "Scissors" },
        { korean: "젓가락", romanization: "jeotgarak", meaning: "Chopstick" },
        { korean: "숟가락", romanization: "sutgarak", meaning: "Spoon" },
        { korean: "수저", romanization: "sujeo", meaning: "Spoon and chopstick" },
        { korean: "계산기", romanization: "gyesangi", meaning: "Calculator" },
        { korean: "쓰레기통", romanization: "sseuregitong", meaning: "Garbage bin" },
        { korean: "건강보험증", romanization: "geongang bheomjeung", meaning: "Health insurance card" },
        { korean: "신분증", romanization: "sinbunjeung", meaning: "Resident card" },
        { korean: "신용카드", romanization: "sinyong kadeu", meaning: "Credit card" },
        { korean: "교통카드", romanization: "gyotong kadeu", meaning: "Transport card" },
        { korean: "학생증", romanization: "haksaengjeung", meaning: "School ID" },
        { korean: "사원증", romanization: "sawonjeung", meaning: "Company ID" },
        { korean: "운전면허증", romanization: "unjeon myeonheojeung", meaning: "Driver's license" },
        { korean: "신문", romanization: "sinmun", meaning: "Newspaper" },
        { korean: "돈", romanization: "don", meaning: "Money" },
        { korean: "카드", romanization: "kadeu", meaning: "Card" },
        { korean: "우표", romanization: "upyo", meaning: "Stamp" },
        { korean: "명함", romanization: "myeongham", meaning: "Calling card" },
        { korean: "여권", romanization: "yeogwon", meaning: "Passport" },
        { korean: "우산", romanization: "usan", meaning: "Umbrella" },
        { korean: "모자", romanization: "moja", meaning: "Hat/Cap" },
        { korean: "장갑", romanization: "janggap", meaning: "Gloves" },
        { korean: "바지", romanization: "baji", meaning: "Pants" },
        { korean: "치마", romanization: "chima", meaning: "Skirt" },
        { korean: "시계", romanization: "sigye", meaning: "Clock" },
        { korean: "거울", romanization: "geoul", meaning: "Mirror" },
        { korean: "지도", romanization: "jido", meaning: "Map" },
        { korean: "사전", romanization: "sajeon", meaning: "Dictionary" },
        { korean: "열쇠", romanization: "yeolsoe", meaning: "Key" },
        { korean: "지폐", romanization: "jipye", meaning: "Paper money" },
        { korean: "영화표", romanization: "yeonghwapyo", meaning: "Movie ticket" },
        { korean: "영수증", romanization: "yeongsujeung", meaning: "Receipt" },
        { korean: "양말", romanization: "yangmal", meaning: "Socks" },
        { korean: "운동화", romanization: "undonghwa", meaning: "Running shoes" },
        { korean: "지갑", romanization: "jigap", meaning: "Wallet" },
        { korean: "옷/의류", romanization: "ot/uiryu", meaning: "Clothes" },
        { korean: "꽃", romanization: "kkot", meaning: "Flower" },
        { korean: "책/도서", romanization: "chaek/doseo", meaning: "Book" },
        { korean: "공", romanization: "gong", meaning: "Ball" },
        { korean: "고무장화", romanization: "gomu janghwa", meaning: "Rubber boots" },
        { korean: "고무장갑", romanization: "gomu janggap", meaning: "Rubber gloves" },
        { korean: "귀덮개", romanization: "gwideomgae", meaning: "Ear cover" },
        { korean: "가족사진", romanization: "gajok sajin", meaning: "Family picture" },
        { korean: "화장품", romanization: "hwajanpum", meaning: "Cosmetic products" },
        { korean: "빗", romanization: "bit", meaning: "Brush" },
        { korean: "헤어드라이어", romanization: "heeo deuraiyeo", meaning: "Hair dryer" },
        { korean: "베개", romanization: "begae", meaning: "Pillow" },
        { korean: "이불", romanization: "ibul", meaning: "Blanket" },
        { korean: "린스", romanization: "rinseu", meaning: "Conditioner" },
        { korean: "샴푸", romanization: "syampu", meaning: "Shampoo" },
        { korean: "비누", romanization: "binu", meaning: "Soap" },
        { korean: "칫솔", romanization: "chitsol", meaning: "Toothbrush" },
        { korean: "치약", romanization: "chiyak", meaning: "Toothpaste" },
        { korean: "수건", romanization: "sugeon", meaning: "Towel" },
        { korean: "면도기", romanization: "myeondogi", meaning: "Razor" },
        { korean: "휴지", romanization: "hyuji", meaning: "Toilet paper" },
        { korean: "컵", romanization: "keop", meaning: "Cup" },
        { korean: "의류", romanization: "uiryu", meaning: "Clothing" },
        { korean: "티셔츠", romanization: "tisyeocheu", meaning: "T-shirt" },
        { korean: "잠바", romanization: "jamba", meaning: "Jacket" },
        { korean: "구두/신발", romanization: "gudu/sinbal", meaning: "Shoes" },
        { korean: "슬리퍼/신발화", romanization: "seullipeo/sinbalhwa", meaning: "Slippers" },
        { korean: "장화", romanization: "janghwa", meaning: "Rain boots" },
        { korean: "양말", romanization: "yangmal", meaning: "Sacks" },
        { korean: "목도리", romanization: "mokdori", meaning: "Scarf" }
    ],

    // MODE OF TRANSPORTATION
    "Mode of Transportation": [
        { korean: "기차", romanization: "gicha", meaning: "Train" },
        { korean: "자전거", romanization: "jajeongeo", meaning: "Bicycle" },
        { korean: "비행기", romanization: "bihaenggi", meaning: "Airplane" },
        { korean: "지하철", romanization: "jihacheol", meaning: "Subway" },
        { korean: "자동차", romanization: "jadongcha", meaning: "Car" },
        { korean: "배", romanization: "bae", meaning: "Boat/Ship" },
        { korean: "마을 버스", romanization: "maeul beoseu", meaning: "Shuttle bus (in-town)" },
        { korean: "시내버스", romanization: "sinaebeoseu", meaning: "Intercity bus" },
        { korean: "시외/고속버스", romanization: "siwoe/gosokbeoseu", meaning: "Express bus" },
        { korean: "버스터미널", romanization: "beoseu teomineol", meaning: "Bus terminal" },
        { korean: "택시 승강장", romanization: "taeksi seunggangjiang", meaning: "Taxi stop" },
        { korean: "기차역", romanization: "gichayeok", meaning: "Train station" },
        { korean: "지하철역", romanization: "jihacheol yeok", meaning: "Subway station" }
    ],

    // ELECTRONIC APPLIANCES
    "Electronic Appliances": [
        { korean: "자동판매기/자판기", romanization: "jadong panmaegi/japangi", meaning: "Vending machine" },
        { korean: "자동인출기", romanization: "jadong inchulgi", meaning: "ATM machine" },
        { korean: "선풍기", romanization: "seonpunggi", meaning: "Electric fan" },
        { korean: "온도계", romanization: "ondogye", meaning: "Thermometer" },
        { korean: "청소기", romanization: "cheongsogi", meaning: "Vacuum cleaner" },
        { korean: "세탁기", romanization: "setakgi", meaning: "Washing machine" },
        { korean: "전화기", romanization: "jeonhwagi", meaning: "Telephone" },
        { korean: "냉장고", romanization: "naengjanggo", meaning: "Refrigerator" },
        { korean: "가습기", romanization: "gaseupgi", meaning: "Humidifier" },
        { korean: "휴대전화", romanization: "hyudae jeonhwa", meaning: "Cellphone" },
        { korean: "전자 레인지", romanization: "jeonja reinji", meaning: "Microwave" },
        { korean: "밥솥", romanization: "bapsot", meaning: "Rice cooker" },
        { korean: "사진기", romanization: "sajingi", meaning: "Camera" },
        { korean: "난로", romanization: "nallo", meaning: "Heater" },
        { korean: "다리미", romanization: "darimi", meaning: "Iron" },
        { korean: "환풍기", romanization: "hwanpunggi", meaning: "Ventilator" },
        { korean: "복사기", romanization: "boksagi", meaning: "Copier machine" }
    ],

    // FURNITURE
    "Furniture": [
        { korean: "가구", romanization: "gagu", meaning: "Furniture" },
        { korean: "서류함", romanization: "seoryuham", meaning: "Filing cabinet" },
        { korean: "보관함", romanization: "bogwanham", meaning: "Storage box/Locker" },
        { korean: "우체통", romanization: "uchetong", meaning: "Mailbox" },
        { korean: "옷장", romanization: "otjang", meaning: "Closet" },
        { korean: "책장/책꽂", romanization: "chaekjang/chaekkkot", meaning: "Bookshelf" },
        { korean: "침대", romanization: "chimdae", meaning: "Bed" },
        { korean: "의자", romanization: "uija", meaning: "Chair" },
        { korean: "서랍장", romanization: "seorapjang", meaning: "Drawer" },
        { korean: "책상", romanization: "chaeksang", meaning: "Study table" },
        { korean: "밥상", romanization: "bapsang", meaning: "Dining table" }
    ],

    // FRUIT AND FOOD
    "Fruit and Food": [
        { korean: "사과", romanization: "sagwa", meaning: "Apple" },
        { korean: "오렌지/귤", romanization: "orenji/gyul", meaning: "Orange" },
        { korean: "포도", romanization: "podo", meaning: "Grape" },
        { korean: "수박", romanization: "subak", meaning: "Watermelon" },
        { korean: "딸기", romanization: "ttalgi", meaning: "Strawberry" },
        { korean: "배", romanization: "bae", meaning: "Pear" },
        { korean: "물", romanization: "mul", meaning: "Water" },
        { korean: "주스", romanization: "juseu", meaning: "Juice" },
        { korean: "우유", romanization: "uyu", meaning: "Milk" },
        { korean: "빵", romanization: "ppang", meaning: "Bread" },
        { korean: "라면", romanization: "ramyeon", meaning: "Instant noodles" },
        { korean: "과자", romanization: "gwaja", meaning: "Snacks" },
        { korean: "아이스크림", romanization: "aiseukeurim", meaning: "Ice cream" },
        { korean: "음식", romanization: "eumsik", meaning: "Food" },
        { korean: "곡식", romanization: "goksik", meaning: "Grains" },
        { korean: "채소/야채", romanization: "chaeso/yachae", meaning: "Vegetables" },
        { korean: "반찬", romanization: "banchan", meaning: "Side dish" }
    ],

    // PLACES
    "Places": [
        { korean: "회사", romanization: "hoesa", meaning: "Workplace" },
        { korean: "사무실", romanization: "samusil", meaning: "Office" },
        { korean: "화장실", romanization: "hwajangsil", meaning: "Restroom" },
        { korean: "식당", romanization: "sikdang", meaning: "Restaurant" },
        { korean: "집/댁", romanization: "jip/daek", meaning: "House" },
        { korean: "기숙사", romanization: "gisuksa", meaning: "Dormitory" },
        { korean: "세탁소", romanization: "setakso", meaning: "Laundromat" },
        { korean: "미용실", romanization: "miyongsil", meaning: "Hair salon" },
        { korean: "시장", romanization: "sijang", meaning: "Market" },
        { korean: "마트", romanization: "mateu", meaning: "Mart" },
        { korean: "편의점", romanization: "pyeonuijeom", meaning: "Convenient store" },
        { korean: "슈퍼마켓", romanization: "syupeo maket", meaning: "Supermarket" },
        { korean: "공중전화", romanization: "gongjung jeonhwa", meaning: "Phonebooth" },
        { korean: "소방서", romanization: "sobangso", meaning: "Fire station" },
        { korean: "공장", romanization: "gongjang", meaning: "Factory" },
        { korean: "경찰서", romanization: "gyeongchalso", meaning: "Police station" },
        { korean: "회사", romanization: "hoesa", meaning: "Company" },
        { korean: "책방/책 가게/서점", romanization: "chaekbang/chaek gage/seojeom", meaning: "Book store" },
        { korean: "도서관", romanization: "doseogwan", meaning: "Library" },
        { korean: "버스 정류장", romanization: "beoseu jeongnyujang", meaning: "Bus station" },
        { korean: "주차장", romanization: "juchajang", meaning: "Parking lot" },
        { korean: "건물", romanization: "geonmul", meaning: "Building" },
        { korean: "농장", romanization: "nongjang", meaning: "Farm" },
        { korean: "병원", romanization: "byeongwon", meaning: "Hospital" },
        { korean: "우체국", romanization: "ucheguk", meaning: "Post office" },
        { korean: "약국", romanization: "yakguk", meaning: "Pharmacy" },
        { korean: "영화관", romanization: "yeonghwagwan", meaning: "Movie theater" },
        { korean: "은행", romanization: "eunhaeng", meaning: "Bank" },
        { korean: "학교", romanization: "hakgyo", meaning: "School" },
        { korean: "공원", romanization: "gongwon", meaning: "Park" },
        { korean: "부엌", romanization: "bueok", meaning: "Kitchen" },
        { korean: "돼지우리", romanization: "dwaejiuri", meaning: "Piggery" },
        { korean: "양계장", romanization: "yanggyejang", meaning: "Chicken farm" },
        { korean: "축사", romanization: "chuksa", meaning: "Poultry/Barn" },
        { korean: "교실", romanization: "gyosil", meaning: "Classroom" },
        { korean: "공항", romanization: "gonghang", meaning: "Airport" },
        { korean: "고향", romanization: "gohyang", meaning: "Hometown" },
        { korean: "노래방", romanization: "noraebang", meaning: "Karaoke" },
        { korean: "PC 방", romanization: "PC bang", meaning: "Internet cafe" },
        { korean: "지하", romanization: "jiha", meaning: "Basement" },
        { korean: "계단", romanization: "gyedan", meaning: "Stairs" }
    ]
};
